title: Puppies are awesome
author: Me
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  So my website is about puppies. 
theme: minima
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
